# -*- coding: utf-8 -*-
"""python-scraping-kadai1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J1B859rRhuFLCg1HJLbKlY4ZYjmZz9IE
"""

import requests
from bs4 import BeautifulSoup

# URLの設定
url = "https://news.yahoo.co.jp/articles/2be699694f28a4e15bfe79c2dffa928165dbb216"

# URLをGET
response = requests.get(url)

# レスポンスのテキストをsoupに代入
soup = BeautifulSoup(response.text, "html.parser")

# 本文の抽出
content1 = soup.select_one("#uamods > div.article_body.highLightSearchTarget > div:nth-child(2)")
content2 = soup.select_one("#uamods > div.article_body.highLightSearchTarget > div:nth-child(3)")

# 本文のテキストを代入
title_text = content1.text + "\n" + content2.text

# 本文のテキストを出力
print(title_text)

