# -*- coding: utf-8 -*-
"""python-scraping-kadai3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-DMvr8yNQQmy2RhRJU-UN-rhxe-zD3Rl
"""

pip install selenium; apt install fonts-ipafont-gothic

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from getpass import getpass

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

chrome_driver = webdriver.Chrome(options=chrome_options)

# ログインボタンをクリック
chrome_driver.get("https://terakoya.sejuku.net/register")

wait = WebDriverWait(chrome_driver, 30)

header_login_button = wait.until(
    EC.visibility_of_element_located(
        (By.CSS_SELECTOR,
         "#root > header > div.sc-ktaQEB.cYQmJQ")
    )
)

header_login_button.click()

# 認証情報の入力
email_address = getpass("メールアドレスを入力してください")
password = getpass("パスワードを入力してください")

parent_element = chrome_driver.find_element(By.CSS_SELECTOR, ".sc-pyfCe.cZfPwB")
email_input = parent_element.find_element(By.NAME, "email")
password_input = parent_element.find_element(By.NAME, "password")

email_input.send_keys(email_address)
password_input.send_keys(password)


# ログインする
from_login_button = wait.until(
    EC.visibility_of_element_located(
        (By.CSS_SELECTOR,
         "#root > div.sc-pyfCe.cZfPwB > div.sc-kDvujY.eCJBhf > div.sc-eDWCr.dePrRH > button")
    )
)

from_login_button.click()

wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, "nav > img")))


# アカウントボタンをクリック
account_button = wait.until(
    EC.visibility_of_element_located(
        (By.CSS_SELECTOR,
         "#root > div.sc-llFzvR.kgFOA-D > div > div > header > div.sc-cnMZnH.bfhwp > div.sc-cCmLNy.iIKLcI > div.sc-jeToga.lgFoIz")
    )
)

account_button.click()

# アカウント設定ボタンをクリック
account_set_button = wait.until(
    EC.visibility_of_element_located(
        (By.CSS_SELECTOR,
         "#root > div.sc-llFzvR.kgFOA-D > div > div > header > div.sc-fpktUn.ictklM > ul > a:nth-child(1) > li.sc-eQVdPn.dFGByf")
    )
)

account_set_button.click()

# 編集ボタンをクリック
account_mod_button = wait.until(
    EC.visibility_of_element_located(
        (By.CSS_SELECTOR,
         "#root > div.sc-jNVCqq.kXoFcu > div > div > main > div > div.sc-qrGtj.cEtYDd > button.sc-eDvSVe.cnuKRu.sc-fmsHFP.laUpbW")
    )
)

account_mod_button.click()

# 自己紹介を入力
self_message = "プログラミング学習中です！今はスクレイピングに挑戦しています！"
self_element = chrome_driver.find_element(By.CSS_SELECTOR, "#root > div.sc-jNVCqq.kXoFcu > div > div > main > div > div.sc-qrGtj.cEtYDd > div:nth-child(9) > div.sc-lbeivL.geQcsg > textarea")

self_element.clear()
self_element.send_keys(self_message)


# 更新するボタンをクリック
mod_button = wait.until(
    EC.visibility_of_element_located(
        (By.CSS_SELECTOR,
         "#root > div.sc-jNVCqq.kXoFcu > div > div > main > div > div.sc-qrGtj.cEtYDd > button.sc-eDvSVe.iklejs.sc-eraWZj.KMhqk")
    )
)

mod_button.click()

# 画面のスクリーンショットを取得
chrome_driver.save_screenshot("screenshot.png")

# Chromeを閉じる
chrome_driver.quit()

